name: bookswap
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  
  # State Management
  provider: ^6.1.2
  
  # UI and Images
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0

# Flutter packages.
flutter:

  uses-material-design: true

